const amod = require("./moda");
const bmod = require("./modb");
const cmod = require('./modc');
const dmod = require('./modd');
const emod = require("./mode");
const fmod = require('./modf');
const eemod = new emod.mode();
console.log(amod.aa);
console.log(bmod.calcRoot(2));
const obj = new cmod.Cars("Punto", "Fiat");
console.log(JSON.stringify(obj));
const obja = new dmod.Books("Ramayan", "Valmiki");
console.log(JSON.stringify(obja));
fmod.ffff();
eemod.funa();
eemod.funb();
eemod.func();
const objc = new eemod.Novels("Adventures of tom sawyer", "Mark Twain");
console.log(JSON.stringify(objc));
